version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: filesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/filesDB
    env_file:
      - .env
